### ISSUE TITLE
Add README.md files to individual SDKs

### ISSUE THREAD

**Issue by panarasi** [Microsoft/mobile-center-sdk-react-native#10]
When published, the individual SDKs do not have a README. I would suggest adding a README to each SDK folder so that they are present when they are published to npm.

The README could also have all the APIs that we currently show in the documentation.

**Comment by TroubleMakerBen** [comment]
Hey @panarasi,

As I wrote [in the other issue](https://github.com/Microsoft/mobile-center-sdk-react-native/issues/14) we're currently looking into how we can improve onboarding!
Thanks so much!
Benny

**Comment by dhei** [comment]
Fixed by #83
