### ISSUE TITLE
Android only link?

### ISSUE THREAD

**Issue by FredyC** [Microsoft/mobile-center-sdk-react-native#104]
Apparently, it's not possible to link mobile-center to Android only project. When I try it I end up with following error.

```bash
react-native link mobile-center
Scanning 604 folders for symlinks in D:\workspace\tracker2\node_modules (65ms)
D:\workspace\tracker2\node_modules\mobile-center-link-scripts\src\ios\index.js:24
    throw Error(`
    ^

Error:
        Could not find AppDelegate.m file for this project, so could not add the framework for iOS.
        You may have to add the framework manually.

    at Object.<anonymous> (D:\workspace\tracker2\node_modules\mobile-center-link-scripts\src\ios\index.js:24:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\workspace\tracker2\node_modules\mobile-center-link-scripts\src\index.js:3:10)
    at Module._compile (module.js:573:30)
D:\workspace\tracker2\node_modules\react-native\local-cli\core\makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/mobile-center/scripts/prelink" command
    at ChildProcess.prelink (D:/workspace/tracker2/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by dhei** [comment]
Hey @FredyC,

It's true that we don't support `react-native link` for android only project at this moment. But you can still link it manually.

Let's say you want to use **mobile-center-analytics** package, here are the steps to link android manually:

(1) In /android/settings.gradle, add the following code:
```gradle
include ':mobile-center-analytics'
project(':mobile-center-analytics').projectDir = new File(rootProject.projectDir, '../node_modules/mobile-center-analytics/android')
```
(2) In /android/app/build.gradle, add the following code inside `dependencies`:
```gradle
compile project(':mobile-center-analytics')
```
(3) In /android/app/src/main/java/com/starter/MainApplication.java, add the reference to mobile-center package and initialize it in `getPackages()` like this:
```java
import com.microsoft.azure.mobile.react.mobilecenter.RNMobileCenterPackage;
... ...
... ...
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
              new RNMobileCenterPackage(MainApplication.this, "ALWAYS_SEND") 
      );
    }
```
(4) Create a new json file at /android/app/src/main/assets/mobile-center-config.json, with the following content. (If you're not sure where to find app_secret, you can find it on the "Getting Started" page of your app on mobile center portal)
```json
{
    "app_secret": <app-secret-of-your-mobile-center-android-app>
}
```
Note that in step 3, you can pass in "ALWAYS_SEND" to allow mobile-center-analytics automatic track user activities, or alternatively "ENABLE_IN_JS" to track user activities in JavaScript code.

The above example works for **mobile-center-analytics**, but should be very similar to other mobile center modules (e.g. mobile-center-push, mobile-center-crashes, mobile-center).

Let us know if this helps or unblocks you.

**Comment by FredyC** [comment]
@dhei Thanks. I did a quite different workaround. Just modified the file in node_modules that does the checking to not throw an error and then it went through just fine. It threw some other error later for iOS, but it has linked it for Android correctly.

**Comment by dhei** [comment]
@FredyC Glad it worked for you. We will better support this scenario in the near future.
