### ISSUE TITLE
[Feature request] Get Build Number

### ISSUE THREAD

**Issue by devbriguy** [Microsoft/mobile-center-sdk-react-native#116]
I want to be able to display the auto incremented build number seen in the email notification. It exposed in JS like how `MobileCenter.getInstallId()` is.

**Comment by devbriguy** [comment]
I found out that the Mobile Center API exposes this if you use: `GET /v0.1/apps/{owner_name}/{app_name}/releases` this returns an array of release data with an id which in turn is the build number I mentioned in the email.

**Comment by guperrot** [comment]
Hi @devbriguy this repository issues covers only the React Native SDK.
For APIs or other services support, please use our support button from the Mobile Center portal.
