### ISSUE TITLE
Push via API

### ISSUE THREAD

**Issue by tendolukwago** [Microsoft/mobile-center-sdk-react-native#119]
Is there an API to push notifications programmatically? If not is there a time frame of when an endpoint might be available? Or are there any examples of how to integrate this with a third party application?

**Comment by guperrot** [comment]
Hi, you are asking an API related question to the React Native SDK repository. People contributing on SDKs are usually not able to answer non SDK related questions so Intercom support is recommended for every non SDK question.

There is an [API](https://docs.microsoft.com/en-us/mobile-center/api-docs/) to push notifications but I have not used it myself. If you have a questions on the docs I recommend the support button from the Mobile Center portal.
