### ISSUE TITLE
Add beacon label to React Native questions

### ISSUE THREAD

**Issue by panarasi** [Microsoft/mobile-center-sdk-react-native#12]
The current question just say "What is the android key" - this can get confusing when `react-native link` is called with multiple plugins. Have a way to show that questions are specific to a Mobile Center SDK.

**Comment by BretJohnson** [comment]
@panarasi Can you give a real life example where you've found this to be an issue. What text would you suggest instead? Thx.

**Comment by BretJohnson** [comment]
I added this is the most recent SDK update.  There's a `Configuring Mobile Center Crashes` or `Configuring Mobile Center Analytics` line output first when running the react-native link.

**Comment by panarasi** [comment]
This happened when I installed a bunch of SDKs, nad then did `react-native link`. I think this text should be fine.  Thanks
