### ISSUE TITLE
RNMobileCenterShared (0.9.1) Download link broken

### ISSUE THREAD

**Issue by rad182** [Microsoft/mobile-center-sdk-react-native#128]
Hi when doing `react-native link mobile-center` I'm getting this error it seems that download link for 0.9.1 is broken.

```
Installing RNMobileCenterShared (0.9.1)

[!] Error installing RNMobileCenterShared
[!] /usr/bin/curl -f -L -o /var/folders/mr/mfskz4mn4hx5c9vclqqwj2280000gn/T/d20170930-14300-szr8lr/file.zip https://github.com/Microsoft/MobileCenter-SDK-React-Native/releases/download/0.9.1/MobileCenter-SDK-ReactNative-iOS-Pod-0.9.1.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   196    0   196    0     0    251      0 --:--:-- --:--:-- --:--:--   251
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by guperrot** [comment]
Hi, 0.9.1 has been unpublished from npm due to a serious bug. Unfortunately the cocoapods component can not be unpublished.

0.9.0 is still the last stable version, please use that one.

**Comment by brunocascio** [comment]
Hi @guperrot,

 Is there some guide in order to use 0.9.0 in this package?

**Comment by dhei** [comment]
@brunocascio The latest version is [0.9.0](https://github.com/Microsoft/mobile-center-sdk-react-native/releases/tag/0.9.0). Change all the mobile-center-* package version in your package.json to 0.9.0 should resolve any issue with `react-native link`. Let me know if this resolve your issue or not. We're releasing v0.9.2 very soon.

**Comment by brunocascio** [comment]
@dhei,

I've tried that before and it does not work to me. However, I think it was a problem with my `yarn.lock` file. 

I will keep you in touch on this issue soon.

Thanks in advance!

**Comment by dhei** [comment]
Hey @brunocascio, we skipped v0.9.2 and [v0.10.0](https://github.com/Microsoft/mobile-center-sdk-react-native/releases/tag/0.10.0) of mobile center react native sdk is out. Let us know if you still have any problem of using mobile center sdk. I will close this issue, please feel free to re-open it.
