### ISSUE TITLE
Align manual installation steps to iOS SDKs

### ISSUE THREAD

**Issue by panarasi** [Microsoft/mobile-center-sdk-react-native#14]
The current Mobile Center iOS SDK needs the libraries in the vendor folder, while React Native says that the libraries can be added to the top level folder. 
Can this SDK be similar to the native SDK ?

**Comment by TroubleMakerBen** [comment]
Hey @panarasi,

Thank you for your feedback. We're currently improving the Documentation experience and we're looking into how we can bring the RN SDK closer to the native iOS one.

Best,
Benny

**Comment by guperrot** [comment]
Fixed on docs site.
