### ISSUE TITLE
Adding MobileCenter pod to Podfile is fragile

### ISSUE THREAD

**Issue by sharnik** [Microsoft/mobile-center-sdk-react-native#17]
# Problem

When adding the MobileCenter dependencies to the `Podfile` it's assumed that the file contains a line:
```
# Pods for …
```

If a Podfile doesn't contain this string, the script blows up with `undefined property 0 on null` on this line: https://github.com/Microsoft/mobile-center-sdk-react-native/blob/master/mobile-center-link-scripts/src/ios/PodFile.js#L26

# Solution

I don't know what could be a more reliable way to insert it 😕

Maybe at least it would be nice to give a better error message explaining the issue, instead of throwing `undefined property 0 on null`?

**Comment by dvisco** [comment]
Agree this burned me as well. It would be nice to have outputted lines needed to be manually added to the `Podfile` to continue with using CocoaPods. I ended up having to read the source to sort out which versions it had been attempting to install.

**Comment by panarasi** [comment]
Do you guys have a suggestion on how we can do this better ? 

cc @BretJohnson

**Comment by sharnik** [comment]
I was thinking that as an easy first step just improve an error message. 

When we can't find the string `# Pods for …` in the Podfile, just print instructions explaining what happened and that insterting `# Pods for MobileCenter` into Podfile will make it work properly.

I know that's not optimal, but I don't think a bulletproof solution is possible (Podfiles are basically just Ruby source code files) and haveing a good error message explaining the fix would be enough for me.

**Comment by BretJohnson** [comment]
Thanks, @sharnik.  I implemented a fix like you suggested, which is in the latest update.
