### ISSUE TITLE
Technically feasible to depend only on NPM instead of CocoaPods?

### ISSUE THREAD

**Issue by jonrh** [Microsoft/mobile-center-sdk-react-native#25]
This is more like a question (maybe feature request) so please feel free to close it, I apologise if this is not the right medium.

Is it technically feasible/possible to not rely on CocoaPods for the Mobile Center SDK? Instead could *mobile-center-analytics* and *mobile-center-crashes* only rely on the NPM package manager? If that would be possible it would provide an easier way to update published apps in the app store that use [CodePush](https://microsoft.github.io/code-push/). For example, the other day there was an update from v0.1.5 to v0.2.2. Updating would then I assume require a resubmission to the Apple App store.

I imagine that there is a good reason why CocoaPods is required that I'm not seeing but wanted to bring it up just in case. Keep up the good work 👍 

**Update**: After thinking some more about this I think it wouldn't change anything in regards to CodePush. When native code (Obj-C) gets updated in libraries, one way or another a recompile is necessary meaning a resubmission would be required.

**Comment by axemclion** [comment]
@BretJohnson Just told me that if you use MobileCenter build, Pods are automatically installed, so you don't have to check in the pods if you are using the build service.
