### ISSUE TITLE
Error while linking SDKs

### ISSUE THREAD

**Issue by vinodr** [Microsoft/mobile-center-sdk-react-native#30]
Hi, I am getting the following error while trying to link the SDKs:

(node:41602) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property '0' of null.

Not sure if it's just me that's getting this error. I can manually link the SDKs for now but just wanted to report the issue so it could be fixed. May be a better error message would help.

**Comment by TroubleMakerBen** [comment]
Hey Vinodr,

Thanks for getting in touch and apologies for the long silence on this. We are going to be more responsive in the future.
Which SDK version and RN toolchain are you using? This info really helps in reproducing the issue.

Best,
Benny

**Comment by madmax983** [comment]
Hi Benny,

Apologies for the late follow-up on this. 

SDK version: 0.4.0
react-native-cli: 2.0.1
react-native: 0.35.0

**Comment by TroubleMakerBen** [comment]
Hey @madmax983,

 no worries! Have you tried the latest SDK release?

Best,
Benny

**Comment by madmax983** [comment]
Hi Benny,

Updated to 0.5.0. Here is my full console output (some tokens may have been changed to protect their identities):

` .   $ react-native link
    Configuring Mobile Center Analytics
    ? What is the Android App Secret? *SUPER_SECRET*
    App Secret for Android written to  android/app/src/main/assets/mobile-center-config.json
    rnpm-install info Android module mobile-center-analytics is already linked 
    rnpm-install info Linking mobile-center-analytics ios dependency 
    rnpm-install WARN ERRGROUP Group 'Libraries' does not exist in your XCode project. We have 
    created it automatically for you.
    rnpm-install info iOS module mobile-center-analytics has been successfully linked 
    ? What is the iOS App Secret? *SUPER_SECRET*
    App Secret for iOS written to ios/Kenandy/MobileCenter-Config.plist
    ? For the iOS app, should user tracking be enabled automatically? Enable Automat
ically
    (node:16733) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 
TypeError: Cannot read property '0' of null
    Configuring Mobile Center Crashes
    ? What is the Android App Secret? *SUPER_SECRET*
    App Secret for Android written to  android/app/src/main/assets/mobile-center-config.json
    rnpm-install info Android module mobile-center-crashes is already linked 
    rnpm-install info Linking mobile-center-crashes ios dependency 
    rnpm-install info iOS module mobile-center-crashes has been successfully linked 
    ? What is the iOS App Secret? *SUPER_SECRET*
    App Secret for iOS written to ios/Kenandy/MobileCenter-Config.plist
    ? For the iOS app, should crashes be sent automatically, or processed in JavaScr
ipt before being sent? Automatically
    (node:16736) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property '0' of null`

**Comment by guperrot** [comment]
@madmax983 hi, do you have any news on your issue? Any sources to share or a minimalist reproduction scenario?

**Comment by guperrot** [comment]
Closing the issue as no news, will reopen on comment.
