### ISSUE TITLE
Build for Android cannot find dependencies

### ISSUE THREAD

**Issue by bmcmillan** [Microsoft/mobile-center-sdk-react-native#33]
> A problem occurred configuring project ':mobile-center-crashes'.
      > Could not resolve all dependencies for configuration ':mobile-center-crashes:_debugPublishCopy'.
         > Could not find any matches for com.microsoft.azure.mobile:mobile-center-crashes:0.6.+ as no versions of com.microsoft.azure.mobile:mobile-center-crashes are available.
           Required by:
               QGenda:mobile-center-crashes:unspecified
         > Could not find any matches for com.microsoft.azure.mobile.react:mobile-center-react-native:0.3.+ as no versions of com.microsoft.azure.mobile.react:mobile-center-react-na
tive are available.
           Required by:
               QGenda:mobile-center-crashes:unspecified

**Comment by TroubleMakerBen** [comment]
Hey @bmcmillan,

thx for getting in touch. I'm forwarding this to our react native folks!

Best,
Benjamin

**Comment by BretJohnson** [comment]
Hi @bmcmillan. Sorry for the delayed reply. You added a custom debugPublishCopy Gradle task, right? It looks like there's a dependency configuration issue with it of some kind.
What does `./gradlew androidDependencies` (in the `android` directory) output for you?  That could give clues.
You could also try creating a new project (`react-native init TestProject` or similar) and add the Mobile Center SDKs to it.  I think you'll find that works OK. Maybe you can then see from that what's configured differently for the `_debugPublishCopy` task.

**Comment by bmcmillan** [comment]
Hi Bret,

Thanks for the reply. It took me a little while, but I figured out the issue. My build.gradle did not contain jcenter() as a repo for allprojects. I only had jitpack and maven2. Adding jcenter fixed it.
