### ISSUE TITLE
Error when package.json name doesn't match iOS folder

### ISSUE THREAD

**Issue by ricklove** [Microsoft/mobile-center-sdk-react-native#35]
If the package.json name doesn't equal the iOS folder, the react-link command fails.

### Suggestion

From https://github.com/Microsoft/mobile-center-sdk-react-native/blob/d54ed9768e28ea11e1bdea2d52e03715d4d99c68/mobile-center-link-scripts/src/ios/MobileCenterConfig.js#L43

I suggest modifying this line:

```
var globString = `**/${(pjson && pjson.name ? pjson.name : '*')}.xcodeproj/project.pbxproj`
```

to simply:

```
var globString = `**/*/project.pbxproj`
```

Otherwise, at least include the globString in the error (because the projectsPath list is blank if not found):

```
Could not locate the xcode project to add MobileCenter-Config.plist file to. 
                Looked in paths - 
                ${JSON.stringify(globString)}
```

**Comment by BretJohnson** [comment]
I think that change makes sense, though there are also some places in the Mobile Center build where we assume the "standard" React Native project layout, with the "ios" directory under the directory containing package.json.

@ricklove Can you say more about what your project directory structure is. Partially I'm just curious. Thanks.

**Comment by ricklove** [comment]
I was actually using the ReactXP Hello World sample:

https://github.com/Microsoft/reactxp/tree/master/samples/hello-world

In their project file, the name is `rxp-hello-world` which is standard for npm packages.

But in the ios project file it uses Pascal Case `RXPHelloWorld`

I solved it by removing the dashes in the package name because the case doesn't seem to matter.

**Comment by guperrot** [comment]
Hi this issue should be fixed by https://github.com/Microsoft/mobile-center-sdk-react-native/pull/51, I will let you know when a release will include the change.

**Comment by guperrot** [comment]
Released.
