### ISSUE TITLE
Linking pod error when building using Mobile center builds

### ISSUE THREAD

**Issue by alikor** [Microsoft/mobile-center-sdk-react-native#36]
I get the following errors when i attempt to build my application using mobile center builds just after installing mobile-center-sdk-react-native 

▸ Linking MYAPP
❌  ld: library not found for -lPods-MYAPP
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
▸ Linking MYAPP
❌  ld: library not found for -lPods-MYAPP
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by egunsoma** [comment]
hey guys Im getting a similar error

❌  ld: library not found for -lGTMSessionFetcher
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

All I did was adding Cocoapods to my project. Local builds are fine, both for device and simulator, its only the remote build with Mobile Center that fails.
pls help

**Comment by BretJohnson** [comment]
Hi. It's probably still using the xcproj to build instead of the xcworkspace. After integrating CocaPods, builds need to switch to using the xcworkspace instead.
We're going to make some UI improvements there soon, in the Build UI, but for you can remove the Build configuration and then re-add to resetup that build. I think you'll see that resolves it.
To remove the build configuration use the menu option here:
![image](https://user-images.githubusercontent.com/245892/27153670-5c22659e-5120-11e7-98b4-e975ff200eca.png)

**Comment by dvorakjan** [comment]
I had the same problem and solution provided by BretJohnson works. Thanks very much

**Comment by BretJohnson** [comment]
FYI - We've since made a fix here so that recreating the build configuration isn't needed, you just need to edit the build configuration and then save it (without having to change anything). That's enough for us to update the build rules to now use the xcworkspace, if it's present in the repo.

**Comment by tsemerad** [comment]
I'm getting this same issue, but only when attempting to build my "Staging" custom configuration. I tried what @BretJohnson suggested but that didn't make a difference. I then tried removing and re-creating the build configuration, but it's still giving me the same issue. 

```
▸ Linking MyApp
⚠️  ld: directory not found for option '-L/Users/ci/agent/vstsagent/_work/1/s/ios/build/Build/Products/Debug-iphonesimulator'

❌  ld: library not found for -lPods-MyApp
```

I tried creating a separate branch and re-setting up all of the build configuration, but still no luck. Is it expected to not work with a custom configuration?

**Comment by guperrot** [comment]
Hi, @tsemerad can you create the ticket on Intercom (from portal blue button) as this is not a SDK issue but build service issue which is not on github.

**Comment by KSanthanam** [comment]
@BretJohnson I tried what you suggested (save again). But I get the same error as others. Please find my log here.
Can you please help.

[1_Build.txt](https://github.com/Microsoft/mobile-center-sdk-react-native/files/1366709/1_Build.txt)

**Comment by guperrot** [comment]
Last comment is followed up on Intercom support so will re-close here unless there are some news that could benefit others.

**Comment by KSanthanam** [comment]
@guperrot Is this problem fixed?

**Comment by dhei** [comment]
Hi @KSanthanam, I tried reaching out to you last week on mobile center intercom support (portal blue button) and haven't heard anything back from you yet. 

Which version of Xcode do you use for your project? I noticed you configured Mobile Center Build to use Xcode 8.3.3, you could get this type of error on an Xcode 9 project. If that is the case for you, you can change the Xcode version by following this documentation at https://docs.microsoft.com/en-us/mobile-center/build/ios/first-build/xcode#3-setting-up-your-first-build.

**Comment by KSanthanam** [comment]
@guperrot this issue can be closed. But for those who have similar issues here is the corrective action. The issue arises because of the Parse 1.15.3 as its binary is compiled with XCode 9.0.0 but the Mobile Central I selected was 8.3.3 as per the advice. But once I switched the option to 9.0.0 the problem went away. 
The Parse 1.15.3. Issue is explained [here](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1195)

**Comment by ivanpagac** [comment]
for me it was a mismatch between target version on pods (min 11.0) and the target project (min 8.0)

**Comment by markymc** [comment]
@BretJohnson's solution to recreate the build config in Appcenter worked for me. Definitely would benefit from a UI update on this in the future! Almost two years is a long time to have not fixed this TBH! よろしくお願いします！

**Comment by markymc** [comment]
@MatkovIvan Ah, I must have missed that, thanks. But IMO a note on Github about a function/workaround that isn't described in the UI isn't a reasonable solution. Perhaps making it clear whether the project or workspace is being used (e.g. as it's done for the scheme) in the UI would be nice?
