### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by jaelim-ms** [Microsoft/mobile-center-sdk-react-native#37]
@sopaco [created an issue](https://github.com/Microsoft/mobile-center-sdk-ios/issues/580) on iOS SDK which is a react native issue.

> due to uncaught exception 'NSInvalidArgumentException', reason: '-[MSWrapperSdk initWithWrapperSdkVersion:wrapperSdkName:liveUpdateReleaseLabel:liveUpdateDeploymentKey:liveUpdatePackageHash:]: unrecognized selector sent to instance 0x618000268c00'
```object-c
[RNCrashes registerWithCrashDelegate: [[RNCrashesDelegateAlwaysSend alloc] init]];  // Initialize Mobile Center crashes
  [RNAnalytics registerWithInitiallyEnabled:true];  // Initialize Mobile Center analytics
```

**Comment by jaelim-ms** [comment]
Give more details for the issue, RN SDK is referencing a wrong method [here](https://github.com/Microsoft/mobile-center-sdk-react-native/blob/336d32c65c090e19837797ac22ebf34c66074bf0/RNMobileCenter/ios/RNMobileCenter/RNMobileCenter.m#L28)
[This](https://github.com/Microsoft/mobile-center-sdk-ios/blob/develop/MobileCenter/MobileCenter/Model/MSWrapperSdk.h#L39) is the method in native iOS.

**Comment by BretJohnson** [comment]
This was apparently caused by using the RN Mobile Center SDK alongside a newer version of the iOS native SDK components than the RN SDK depends on.  That kind of version mismatch isn't really supported.
But in any case, we published a RN SDK update earlier this week (0.5.0) that uses the latest native SDKs. So this problem should be gone.

**Comment by StanSarr** [comment]
Hello Guys,
I'm having the same issue with Android (ReactNative), my app crashes on startup since I install the     mobileCenterCrashes. 
```json
"mobile-center-analytics": "^0.5.0",
"mobile-center-crashes": "^0.7.0",
"react-native": "0.44.0",
```

**Comment by BretJohnson** [comment]
You don't want to mix versions like that, with 0.5.0 for analytics and 0.7.0 for crashes. Why don't you:
- `npm uninstall` mobile-center-analytics and mobile-center-crashes
- remove all the Mobile Center SDK components from your Podfile 
- delete Podfile.lock and Pods directory (they'll get regenerated)

Then reinstall:
- `npm install mobile-center mobile-center-analytics mobile-center-crashes --save`
- `react-native link`

See how that works.
