### ISSUE TITLE
RNAnalytics.getEnabled is not a function

### ISSUE THREAD

**Issue by Andreyco** [Microsoft/mobile-center-sdk-react-native#38]
When trying to check `enabled` status, I get error - despite setEnabled works as expected.

SDK version: ^0.4.0
RN version: 0.44.2

**Comment by BretJohnson** [comment]
Thanks for the report. That is a known issue. We'll fix it with the next SDK update, coming (we hope) around end of this week.

**Comment by Andreyco** [comment]
Thanks for info and your hard, awesome work put into this project.
