### ISSUE TITLE
Cannot see my simulated crashes in dashboard

### ISSUE THREAD

**Issue by keshavkaul** [Microsoft/mobile-center-sdk-react-native#45]
I'm simulating a crash in my react-native project in ios simulator but the dashboard isn't being updated with that information.

**Comment by TroubleMakerBen** [comment]
Hey @keshavkaul,
Thanks for getting in touch. Have you disconnected the debugger before you tried to crash the app? CrashReporting on iOS only works when there is no debugger attached.

**Comment by keshavkaul** [comment]
@TroubleMakerBen I have tried the following combinations:
1. `react-native run-ios` on simulator ----- Fail
2. xcode run on simulator and stop debugging and open the app again ------ Fail
3. xcode run on device and stop debugging and open the app again ------- Fail
4. xcode create archive and make an exportable .ipa file and install on device -------- Fail

On android, I'm able to see exceptions in native java code but when I simulate the error in javascript `throw new Error()`, I still see the error being reported in native Java code instead of line of javascript code.

Thanks for the Assist!

**Comment by BretJohnson** [comment]
@keshavkaul To clarify, on iOS you're not seeing that crash reported at all in the web portal, right?

On Android, we unfortunately don't support JavaScript source maps for crashes on Android today--so seeing the line of Java code that crashes, but not JavaScript, is expected there today. But JavaScript call stacks should work on iOS--at least that's the intention.

**Comment by guperrot** [comment]
@keshavkaul if you still can't see ios crashes:

* make sure the xcode debugger is not attached if you are testing native crashes
* make sure you are not in debug config when a javascript exception occurs as this does not trigger a crash a debug, just a red screen

If you are testing with the conditions above and not seeing crash reports, please add the following to your AppDelegate.m in native code part:

```
[MSMobileCenter setLogLevel: MSLogLevelVerbose];
```

before

```
[RNMobileCenter register];
```

Then do a run that a crashes the app without any debugger (neither xcode debbuger nor react native, no red screen or js reload, it has to crash the app as in process exit).

Then restart the app to let app report crashes.

Then fetch the simulator or device logs having `MobileCenter` in it and please attach to this ticket so we can tell you what is wrong.

**Comment by guperrot** [comment]
Also make sure you don't have missing symbols to upload, the portal will tell you about that.

**Comment by guperrot** [comment]
Closing issue as no news, will reopen on new comments.
