### ISSUE TITLE
Provide an api for send crashes to Mobile Center programmatic

### ISSUE THREAD

**Issue by bang88** [Microsoft/mobile-center-sdk-react-native#49]
Hi, there.

We use a little javascript to catch the runtime javascript exceptions and provide a dialog for the end user, the question here is we can capture the javascript error and give a alert for user we have a trouble with our app and the app will not crash since we handle the exception already. but we need to know whats going to here, and we want send these crashes to Mobile center so we can do more job for this kind of crashes.

The code seems like:

```js
const noop = () => {};

export const setJSExceptionHandler = (customHandler = noop, allowedInDevMode = false) => {
  const allowed = allowedInDevMode ? true : !__DEV__;
  if (allowed) {
    global.ErrorUtils.setGlobalHandler(customHandler);
  } else {
    console.log('Skipping setJSExceptionHandler: Reason: In DEV mode and allowedInDevMode = false');
  }
};

export const getJSExceptionHandler = () => global.ErrorUtils.getGlobalHandler();

export default {
  setJSExceptionHandler,
  getJSExceptionHandler
};

```
and use it as:

```
const errorHandler = (e, isFatal) => {
  if (isFatal) {
    Alert.alert('Error`, [
      {
        text: 'OK',
       // TODO 
        onPress:()=> send crashes to mobile center here .
      },
    ])
  } else {
    console.log(e) 
  }
}

setJSExceptionHandler(errorHandler)
```
any thoughts ?

Thanks for the wonderful job.

**Comment by BretJohnson** [comment]
Hi. Mobile Center crashes today doesn't support "handled exceptions", but that feature is definitely on our roadmap. Currently, however, there's not really a way gather and send crashes to Mobile Center without, well, crashing. So I think you'll just want to wait until we have proper support for this feature. I'm not sure of the exact time frame, but I think you'll see it in the next few months.

**Comment by MrLoh** [comment]
@BretJohnson seems like this feature is still not there from looking at the documentation or did I miss something?

**Comment by guperrot** [comment]
Hi @MrLoh, this feature was also requested in #324, it's still open and there is no ETA as of today.
