### ISSUE TITLE
Trouble with iOS and Mobile Center

### ISSUE THREAD

**Issue by nonameolsson** [Microsoft/mobile-center-sdk-react-native#50]
Hi!
I've used Mobile Center with Analytics and Crash before. Now I'm trying to integrate Push. But I'm having some problems with iOS and XCode. It works great on Android though.

What could be the problem?

Here are som error messages:
![screen shot 2017-07-05 at 10 16 41](https://user-images.githubusercontent.com/1493018/27872168-7a4d1020-616d-11e7-953f-ec0fca5dad93.png)
![screen shot 2017-07-05 at 10 13 53](https://user-images.githubusercontent.com/1493018/27872176-84054420-616d-11e7-8b61-1c49677196a3.png)
![screen shot 2017-07-05 at 10 09 34](https://user-images.githubusercontent.com/1493018/27872188-8ccd37c0-616d-11e7-9397-b50287a765fb.png)

**Comment by BretJohnson** [comment]
Hi Andreas. Let's troubleshoot this via the Intercom thread we have going (https://app.intercom.io/a/apps/r33tq287/respond/inbox/conversation/10651761564).

**Comment by nonameolsson** [comment]
Yeah, thanks! That solved my problem.

I'll post my `Podfile` here if someone else encounters the same issue. 
The problem was that I tried to use an old Pod that isn't supported any more.
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'OpusApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpusApp
  pod 'MobileCenter/Push', '~> 0.10.1'
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7'

  target 'OpusAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OpusApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpusApp-tvOS

  target 'OpusApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```
