### ISSUE TITLE
RNMobileCenterShared not found

### ISSUE THREAD

**Issue by mwarger** [Microsoft/mobile-center-sdk-react-native#60]
I get the following during the ios build:

```
/node_modules/mobile-center-analytics/ios/RNAnalytics/RNAnalytics.m:22:9: fatal error: module 'RNMobileCenterShared' not found
@import RNMobileCenterShared;
 ~~~~~~~^~~~~~~~~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **
```

My mobile-center-analytics and mobile-center-crashes packages are both at 0.7.0.

I suspect this has something to do with my podfile dependencies, but I have had no luck searching for the solution.

My pods are declared as 
```
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'
```

Any advice to solve this issue?  Thanks!

**Comment by guperrot** [comment]
Hi, this seems to be the same as #59 you can find the work around there.
Sorry for the inconvenience.
