### ISSUE TITLE
Android RN app crashses after adding mobile-center-push 

### ISSUE THREAD

**Issue by ezekjh** [Microsoft/mobile-center-sdk-react-native#61]
Hi,
I added mobile-center-push package to my RN app. Followed the steps from https://docs.microsoft.com/en-us/mobile-center/sdk/push/react-native-android.

After doing `react-native run-android` on my device the build process finishes without errors but as soon as the app launches it crashes.
This builds and works on the iOS project which I tested on an iPad Pro.

On my package.json I have
 "mobile-center": "^0.7.0",
 "mobile-center-analytics": "^0.7.0",
 "mobile-center-crashes": "^0.7.0",
 "mobile-center-push": "^0.7.0",
 "react": "16.0.0-alpha.6",
 "react-native": "0.44.3"

The device I'm testing on is a Moto Z Play (Android 7.0)
After installing a logging application I could see this error when launching:
_**No static method zzb**_

EDIT:
Was able to make it work by adding this to build.gradle
```
  compile "com.google.firebase:firebase-core:11.0.2"
  compile "com.google.firebase:firebase-messaging:11.0.2"
```

Though the documentation explicitly says not to add them...
Could something have failed with the link process? Tried it several times.

Thanks.

**Comment by guperrot** [comment]
Hi, it seems like the SDK pulled the wrong version of Firebase and thus your work around is indeed correct.

The fix would be to bump those versions in the push SDK gradle next time we release it.

**Comment by guperrot** [comment]
@ezekjh The 0.7.0 SDK is already using version 11.0.2 though, can you temporarily remove your explicit Firebase dependencies and run `./gradlew dependencies` inside the android folder? (and paste the output here so I can check?). Thanks in advance.

**Comment by ezekjh** [comment]
Hi, attached is the output of running `gradlew androidDependencies` on my project.

[log.txt](https://github.com/Microsoft/mobile-center-sdk-react-native/files/1187533/log.txt)

**Comment by guperrot** [comment]
Ok 0.7.0 react native depends on mobile center 0.10.0 which was supposed to depend on firebase 11.0.2 but depends on 11.0.0 instead.

Releasing React Native 0.8.0 will bump native android sdk dependency to 0.11.1 and firebase 11.0.2 which will solve the issue.

Thanks for the follow up.

**Comment by guperrot** [comment]
Released
